#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x687393EE37D128F8 (matthieu@herrb.eu)
#
Name     : libSM
Version  : 1.2.3
Release  : 12
URL      : http://xorg.freedesktop.org/releases/individual/lib/libSM-1.2.3.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libSM-1.2.3.tar.gz
Source99 : http://xorg.freedesktop.org/releases/individual/lib/libSM-1.2.3.tar.gz.sig
Summary  : X Session Management Library
Group    : Development/Tools
License  : MIT-Opengroup
Requires: libSM-lib
Requires: libSM-license
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libxslt-bin
BuildRequires : pkg-config
BuildRequires : pkgconfig(32ice)
BuildRequires : pkgconfig(32uuid)
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(32xproto)
BuildRequires : pkgconfig(32xtrans)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(uuid)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)
BuildRequires : pkgconfig(xtrans)
BuildRequires : xmlto

%description
libSM - X Session Management Library
All questions regarding this software should be directed at the
Xorg mailing list:

%package dev
Summary: dev components for the libSM package.
Group: Development
Requires: libSM-lib = %{version}-%{release}
Provides: libSM-devel = %{version}-%{release}

%description dev
dev components for the libSM package.


%package dev32
Summary: dev32 components for the libSM package.
Group: Default
Requires: libSM-lib32 = %{version}-%{release}
Requires: libSM-dev = %{version}-%{release}

%description dev32
dev32 components for the libSM package.


%package doc
Summary: doc components for the libSM package.
Group: Documentation

%description doc
doc components for the libSM package.


%package lib
Summary: lib components for the libSM package.
Group: Libraries
Requires: libSM-license = %{version}-%{release}

%description lib
lib components for the libSM package.


%package lib32
Summary: lib32 components for the libSM package.
Group: Default
Requires: libSM-license = %{version}-%{release}

%description lib32
lib32 components for the libSM package.


%package license
Summary: license components for the libSM package.
Group: Default

%description license
license components for the libSM package.


%prep
%setup -q -n libSM-1.2.3
pushd ..
cp -a libSM-1.2.3 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1539207889
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check
cd ../build32;
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1539207889
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libSM
cp COPYING %{buildroot}/usr/share/doc/libSM/COPYING
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/SM/SM.h
/usr/include/X11/SM/SMlib.h
/usr/include/X11/SM/SMproto.h
/usr/lib64/libSM.so
/usr/lib64/pkgconfig/sm.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libSM.so
/usr/lib32/pkgconfig/32sm.pc
/usr/lib32/pkgconfig/sm.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/libSM/SMlib.xml
/usr/share/doc/libSM/xsmp.xml

%files lib
%defattr(-,root,root,-)
/usr/lib64/libSM.so.6
/usr/lib64/libSM.so.6.0.1

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libSM.so.6
/usr/lib32/libSM.so.6.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/doc/libSM/COPYING
